name: Build rules

on:
  workflow_dispatch:
  # 每天 2:40 (UTC+8) 触发一次
  schedule:
    - cron: '40 18 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: vpsconfig/convert_rules
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Environment Variables and Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo "BUILDTIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
          echo "REPODIR=$PWD" >> $GITHUB_ENV
          mkdir -p $(dirname ./rule/Clash/Hijacking/Hijacking_OCD_Domain.mrs) && wget -O ./rule/Clash/Hijacking/Hijacking_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Hijacking/Hijacking_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/Hijacking/Hijacking_OCD_IP.mrs) && wget -O ./rule/Clash/Hijacking/Hijacking_OCD_IP.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Hijacking/Hijacking_OCD_IP.mrs
          mkdir -p $(dirname ./rule/Clash/Privacy/Privacy_OCD_Domain.mrs) && wget -O ./rule/Clash/Privacy/Privacy_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Privacy/Privacy_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/Privacy/Privacy_OCD_IP.mrs) && wget -O ./rule/Clash/Privacy/Privacy_OCD_IP.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Privacy/Privacy_OCD_IP.mrs
          mkdir -p $(dirname ./rule/Clash/BlockHttpDNS/BlockHttpDNS_OCD_Domain.mrs) && wget -O ./rule/Clash/BlockHttpDNS/BlockHttpDNS_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/BlockHttpDNS/BlockHttpDNS_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/BlockHttpDNS/BlockHttpDNS_OCD_IP.mrs) && wget -O ./rule/Clash/BlockHttpDNS/BlockHttpDNS_OCD_IP.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/BlockHttpDNS/BlockHttpDNS_OCD_IP.mrs
          mkdir -p $(dirname ./rule/Clash/ChinaMax/ChinaMax_OCD_Domain.mrs) && wget -O ./rule/Clash/ChinaMax/ChinaMax_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/ChinaMax/ChinaMax_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/ChinaMax/ChinaMax_OCD_IP.mrs) && wget -O ./rule/Clash/ChinaMax/ChinaMax_OCD_IP.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/ChinaMax/ChinaMax_OCD_IP.mrs
          mkdir -p $(dirname ./rule/Clash/PrivateTracker/PrivateTracker_OCD_Domain.mrs) && wget -O ./rule/Clash/PrivateTracker/PrivateTracker_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/PrivateTracker/PrivateTracker_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/PrivateTracker/PrivateTracker_OCD_IP.mrs) && wget -O ./rule/Clash/PrivateTracker/PrivateTracker_OCD_IP.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/PrivateTracker/PrivateTracker_OCD_IP.mrs
          mkdir -p $(dirname ./rule/Clash/Telegram/Telegram_OCD_Domain.mrs) && wget -O ./rule/Clash/Telegram/Telegram_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Telegram/Telegram_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/Telegram/Telegram_OCD_IP.mrs) && wget -O ./rule/Clash/Telegram/Telegram_OCD_IP.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Telegram/Telegram_OCD_IP.mrs
          mkdir -p $(dirname ./rule/Clash/OpenAI/OpenAI_OCD_Domain.mrs) && wget -O ./rule/Clash/OpenAI/OpenAI_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/OpenAI/OpenAI_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/OpenAI/OpenAI_OCD_IP.mrs) && wget -O ./rule/Clash/OpenAI/OpenAI_OCD_IP.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/OpenAI/OpenAI_OCD_IP.mrs
          mkdir -p $(dirname ./rule/Clash/Copilot/Copilot_OCD_Domain.mrs) && wget -O ./rule/Clash/Copilot/Copilot_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Copilot/Copilot_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/Copilot/Copilot_OCD_IP.mrs) && wget -O ./rule/Clash/Copilot/Copilot_OCD_IP.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Copilot/Copilot_OCD_IP.mrs
          mkdir -p $(dirname ./rule/Clash/Google/Google_OCD_Domain.mrs) && wget -O ./rule/Clash/Google/Google_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Google/Google_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/Google/Google_OCD_IP.mrs) && wget -O ./rule/Clash/Google/Google_OCD_IP.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Google/Google_OCD_IP.mrs
          mkdir -p $(dirname ./rule/Clash/Apple/Apple_OCD_Domain.mrs) && wget -O ./rule/Clash/Apple/Apple_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Apple/Apple_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/Apple/Apple_OCD_IP.mrs) && wget -O ./rule/Clash/Apple/Apple_OCD_IP.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Apple/Apple_OCD_IP.mrs
          mkdir -p $(dirname ./rule/Clash/TikTok/TikTok_OCD_Domain.mrs) && wget -O ./rule/Clash/TikTok/TikTok_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/TikTok/TikTok_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/OKX/OKX_OCD_Domain.mrs) && wget -O ./rule/Clash/OKX/OKX_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/OKX/OKX_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/Binance/Binance_OCD_Domain.mrs) && wget -O ./rule/Clash/Binance/Binance_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Binance/Binance_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/Speedtest/Speedtest_OCD_Domain.mrs) && wget -O ./rule/Clash/Speedtest/Speedtest_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Speedtest/Speedtest_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/Microsoft/Microsoft_OCD_Domain.mrs) && wget -O ./rule/Clash/Microsoft/Microsoft_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Microsoft/Microsoft_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/Gemini/Gemini_OCD_Domain.mrs) && wget -O ./rule/Clash/Gemini/Gemini_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Gemini/Gemini_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/Claude/Claude_OCD_Domain.mrs) && wget -O ./rule/Clash/Claude/Claude_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Claude/Claude_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/GlobalMedia/GlobalMedia_OCD_Domain.mrs) && wget -O ./rule/Clash/GlobalMedia/GlobalMedia_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/GlobalMedia/GlobalMedia_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/iCloud/iCloud_OCD_Domain.mrs) && wget -O ./rule/Clash/iCloud/iCloud_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/iCloud/iCloud_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/PikPak/PikPak_OCD_Domain.mrs) && wget -O ./rule/Clash/PikPak/PikPak_OCD_Domain.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/PikPak/PikPak_OCD_Domain.mrs
          mkdir -p $(dirname ./rule/Clash/Lan/Lan_OCD_IP.mrs) && wget -O ./rule/Clash/Lan/Lan_OCD_IP.mrs https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/refs/heads/master/rule/Clash/Lan/Lan_OCD_IP.mrs
      # 运行 subconverter, 将 .list 转为 .yaml
      - name: Run subconverter
        run: |
          curl -s https://api.github.com/repos/tindy2013/subconverter/releases \
            | grep "browser_download_url.*subconverter_linux64.tar.gz" \
            | head -n 1 \
            | cut -d '"' -f 4 \
            | xargs wget -q
          tar -xf subconverter_linux64.tar.gz
          ./subconverter/subconverter &
          python3 -m http.server 56290 --bind 127.0.0.1 --directory './rule/' &

      # 运行 mihomo, 将 .txt 转为 .mrs
      - name: Run mihomo
        run: |
          curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases \
            | grep "browser_download_url.*mihomo-linux-amd64-alpha.*.deb" \
            | head -n 1 \
            | cut -d '"' -f 4 \
            | xargs wget -q -O mihomo-linux-amd64-alpha.deb
          sudo apt install --fix-missing ./mihomo-linux-amd64-alpha.deb
          /usr/bin/mihomo &

      - name: Verify environment
        run: |
          if [ ! -f "./script/convert_rules.sh" ]; then
            echo "convert_rules.sh not found. Exiting."
            exit 1
          fi

      # 执行规则转换脚本
      - name: Execute convert script
        run: |
          chmod +x ./script/convert_rules.sh
          ./script/convert_rules.sh

      - name: Commit and Push Changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "Builded on ${{ env.BUILDTIME }}"
            git push origin main
          else
            echo "No changes to commit"
          fi
